version: '3'
services:
   webserver:
       depends_on:
         - dbserver
       image: tomcat
       volumes:
         - webconfig:/tmp
       ports:
         - "8088:8080"
       deploy:
         replicas: 3
   dbserver:
       image: mysql:5.7
       ports:
         - "3306:3306"
volumes:
  webconfig: {}