apiVersion: v1
kind: Pod
metadata:
  name: fronend
  labels:
    tier: frontend-web
spec:
  containers:
    - name: frontendworpress
      image: wordpress
      envFrom:
        - configMapRef:
            name: app-config