apiVersion: v1
kind: Service
metadata:
  name: frontendweb
  lables:
    tire: webapp
spec:
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 8080
  type: NodePort
  selector:
    tier: webapp

