apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: myfrontend
      image: ubuntu
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          value: pink
        - name: APP_COLOR
          valueFrom:
             configMapKeyRef:

        - name: APP_COLOR
            valueFrom:
              secretKeyRef:
