apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-relicaset
spec:
  template:
    metadata:
      name: webapp-frontend
      labels:
        tier: webapp
    spec:
      containers:
        - name: frontend-web
          image: httpd
  replicas: 2
  selector:
     matchLabels:
       tier: webapp
